Update linked_list_test.rb
Currently if you call @list.get_last on an empty list, you get an error, such as "NoMethodError: undefined method `next' for nil:NilClass". This assumes the implemented method uses .next to move the pointer to the end of the list.